name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/spectatord' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore Conan Cache
        id: conan-cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /home/runner/.conan2
            /home/runner/work/spectatord/spectatord/cmake-build
            /home/runner/work/spectatord/spectatord/ska
          key: ${{ runner.os }}-conan

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-11 libiberty-dev

      - name: Build
        run: |
          ./setup-venv.sh
          source venv/bin/activate
          ./build.sh

      - name: Save Conan Cache
        id: conan-cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            /home/runner/.conan2
            /home/runner/work/spectatord/spectatord/cmake-build
            /home/runner/work/spectatord/spectatord/ska
          key: ${{ steps.conan-cache-restore.outputs.cache-primary-key }}
