name: Build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: ${{ github.repository == 'Netflix-Skunkworks/spectatord' }}
    runs-on: ubuntu-latest
    env:
      BUILD_DIR: "cmake-build"
      CC: "gcc-11"
      CXX: "g++-11"
      LANG: "en_US.UTF-8"
    steps:
      - uses: actions/checkout@v3

      - name: Conan+Cmake Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.conan
            ~/work/spectatord/spectatord/cmake-build
          key: ${{ runner.os }}-conan-cmake

      - name: Install System Dependencies
        run: |
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update && sudo apt-get install -y binutils-dev g++-11 libiberty-dev

          echo "==== cmake ===="
          cmake -version

          echo "==== python ===="
          python3 -V

          echo "==== conan ===="
          pip install "conan==1.61.0"
          conan --version
          if [[ ! -f ~/.conan/profiles/default ]]; then conan profile new default --detect; fi
          conan profile update settings.compiler.libcxx=libstdc++11 default

      - name: Install Project Dependencies
        run: |
          conan install . --build=missing --install-folder $BUILD_DIR
          conan source .

      - name: Build spectatord
        run: |
          tools/generate_version.sh > spectator/version.h
          cd $BUILD_DIR
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          echo "==== ldd ===="
          ldd bin/spectatord_main || true

      - name: Test spectatord
        run: |
          cd $BUILD_DIR
          GTEST_COLOR=1 ctest --verbose
